import { index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const createdAt = timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
const updatedAt = timestamp("updated_at", { withTimezone: true }).defaultNow().notNull();

export const userStatus = pgEnum("user_status", ["ACTIVE", "DISABLED"]);
export const memberRole = pgEnum("member_role", ["OWNER", "ADMIN", "MEMBER"]);
export const groupStatus = pgEnum("group_status", ["ACTIVE", "PAUSED", "DISABLED"]);
export const campaignStatus = pgEnum("campaign_status", ["DRAFT", "READY", "RUNNING", "PAUSED", "COMPLETED", "CANCELLED"]);
export const variantStrategy = pgEnum("variant_strategy", ["PRIMARY_ONLY", "ROUND_ROBIN"]);
export const queueStatus = pgEnum("queue_status", ["PENDING", "READY", "OPENED", "AWAITING_CONFIRMATION", "POSTED", "SKIPPED", "FAILED"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), email: varchar("email", { length: 320 }).notNull().unique(),
  passwordHash: text("password_hash"), displayName: varchar("display_name", { length: 120 }).notNull(), avatarUrl: text("avatar_url"),
  status: userStatus("status").default("ACTIVE").notNull(), sessionVersion: integer("session_version").default(0).notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  createdAt, updatedAt, lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
});
export const workspaces = pgTable("workspaces", { id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 120 }).notNull(), ownerId: uuid("owner_id").notNull().references(() => users.id), createdAt, updatedAt });
export const workspaceMembers = pgTable("workspace_members", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: memberRole("role").default("MEMBER").notNull(), createdAt }, (t) => [uniqueIndex("workspace_members_workspace_user_uq").on(t.workspaceId, t.userId), index("workspace_members_user_idx").on(t.userId)]);
export const groups = pgTable("groups", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), createdBy: uuid("created_by").notNull().references(() => users.id), name: varchar("name", { length: 160 }).notNull(), facebookUrl: text("facebook_url").notNull(), category: varchar("category", { length: 80 }), description: text("description"), notes: text("notes"), status: groupStatus("status").default("ACTIVE").notNull(), lastPostedAt: timestamp("last_posted_at", { withTimezone: true }), createdAt, updatedAt }, (t) => [uniqueIndex("groups_workspace_url_uq").on(t.workspaceId, t.facebookUrl), index("groups_workspace_idx").on(t.workspaceId)]);
export const contents = pgTable("contents", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), createdBy: uuid("created_by").notNull().references(() => users.id), name: varchar("name", { length: 160 }).notNull(), body: text("body").notNull(), linkUrl: text("link_url"), createdAt, updatedAt }, (t) => [index("contents_workspace_idx").on(t.workspaceId)]);
export const contentVariants = pgTable("content_variants", { id: uuid("id").defaultRandom().primaryKey(), contentId: uuid("content_id").notNull().references(() => contents.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), body: text("body").notNull(), createdAt, updatedAt });
export const media = pgTable("media", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), contentId: uuid("content_id").references(() => contents.id, { onDelete: "set null" }), storageKey: text("storage_key").notNull().unique(), mimeType: varchar("mime_type", { length: 100 }).notNull(), originalFilename: varchar("original_filename", { length: 255 }).notNull(), sizeBytes: integer("size_bytes").notNull(), createdAt });
export const campaigns = pgTable("campaigns", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), createdBy: uuid("created_by").notNull().references(() => users.id), name: varchar("name", { length: 160 }).notNull(), contentId: uuid("content_id").notNull().references(() => contents.id), status: campaignStatus("status").default("DRAFT").notNull(), variantStrategy: variantStrategy("variant_strategy").default("PRIMARY_ONLY").notNull(), minIntervalSeconds: integer("min_interval_seconds").default(300).notNull(), maxIntervalSeconds: integer("max_interval_seconds").default(600).notNull(), scheduledStartAt: timestamp("scheduled_start_at", { withTimezone: true }), createdAt, startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), updatedAt }, (t) => [index("campaigns_workspace_idx").on(t.workspaceId), index("campaigns_status_idx").on(t.status)]);
export const campaignGroups = pgTable("campaign_groups", { id: uuid("id").defaultRandom().primaryKey(), campaignId: uuid("campaign_id").notNull().references(() => campaigns.id, { onDelete: "cascade" }), groupId: uuid("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }), position: integer("position").notNull(), createdAt }, (t) => [uniqueIndex("campaign_groups_uq").on(t.campaignId, t.groupId)]);
export const queueItems = pgTable("queue_items", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), campaignId: uuid("campaign_id").notNull().references(() => campaigns.id, { onDelete: "cascade" }), groupId: uuid("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }), position: integer("position").notNull(), variantId: uuid("variant_id").references(() => contentVariants.id, { onDelete: "set null" }), status: queueStatus("status").default("PENDING").notNull(), scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), attemptCount: integer("attempt_count").default(0).notNull(), errorCode: varchar("error_code", { length: 80 }), errorMessage: text("error_message"), claimToken: text("claim_token"), claimedAt: timestamp("claimed_at", { withTimezone: true }), createdAt, updatedAt }, (t) => [index("queue_workspace_idx").on(t.workspaceId), index("queue_campaign_idx").on(t.campaignId), index("queue_status_idx").on(t.status), index("queue_scheduled_idx").on(t.scheduledAt)]);
export const postHistory = pgTable("post_history", { id: uuid("id").defaultRandom().primaryKey(), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), campaignId: uuid("campaign_id").notNull().references(() => campaigns.id, { onDelete: "cascade" }), groupId: uuid("group_id").notNull().references(() => groups.id, { onDelete: "cascade" }), queueItemId: uuid("queue_item_id").notNull().references(() => queueItems.id, { onDelete: "cascade" }), status: queueStatus("status").notNull(), facebookPostUrl: text("facebook_post_url"), notes: text("notes"), postedAt: timestamp("posted_at", { withTimezone: true }), createdAt }, (t) => [index("history_workspace_idx").on(t.workspaceId), index("history_campaign_idx").on(t.campaignId), index("history_group_idx").on(t.groupId)]);
export const devices = pgTable("devices", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), tokenHash: text("token_hash").notNull().unique(), createdAt, lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }) }, (t) => [index("devices_user_idx").on(t.userId), index("devices_workspace_idx").on(t.workspaceId), index("devices_token_hash_idx").on(t.tokenHash)]);
export const pairingCodes = pgTable("pairing_codes", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), workspaceId: uuid("workspace_id").notNull().references(() => workspaces.id, { onDelete: "cascade" }), codeHash: text("code_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt });
export const passwordResets = pgTable("password_resets", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt });
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "set null" }), workspaceId: uuid("workspace_id").references(() => workspaces.id, { onDelete: "set null" }), action: varchar("action", { length: 80 }).notNull(), resourceType: varchar("resource_type", { length: 80 }), resourceId: uuid("resource_id"), metadataJson: jsonb("metadata_json").$type<Record<string, unknown>>().default({}).notNull(), createdAt }, (t) => [index("audit_workspace_idx").on(t.workspaceId)]);
export const rateLimits = pgTable("rate_limits", { key: text("key").primaryKey(), count: integer("count").notNull(), resetAt: timestamp("reset_at", { withTimezone: true }).notNull() });
export const emailOutbox = pgTable("email_outbox", { id: uuid("id").defaultRandom().primaryKey(), to: varchar("to", { length: 320 }).notNull(), subject: text("subject").notNull(), body: text("body").notNull(), sentAt: timestamp("sent_at", { withTimezone: true }), createdAt });
